# Setup
title:        Needs Love
tagline:      ""
baseurl:      "/needs-love"
github:       "https://github.com/rseng/needs-love"

# Collections
collections:
  issues:
    output: true
  matched:
    output: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#Others
markdown: kramdown
