name: update-labels

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  UpdateLabels:
    runs-on: ubuntu-latest
    steps:
    - name: Setup python environment
      run: conda create --quiet --name needslove requests
    - name: Update Labels for needs-love or matched
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Absolutely must download specific sha of script
        wget https://raw.githubusercontent.com/rseng/needs-love/88a1bb1ba4ff0ac873654cf4a7ca01e3ff0bb7c8/.github/update-labels.py
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate needslove
        chmod +x update-labels.py
        python update-labels.py
